version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"  # Примечание: порт 3000 снаружи, 80 внутри контейнера
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
  admin:
    build:
      context: ./admin
    ports:
      - "4000:80"  # Примечание: порт 4000 снаружи, 80 внутри контейнера
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro